DROP TABLE IF EXISTS `dynamicrecipes`;
CREATE TABLE `dynamicrecipes`  (
  `id` bigint(250) NOT NULL,
  `count_image` TEXT(65534) NULL DEFAULT NULL,
  `circle_image`TEXT(65534) NULL DEFAULT NULL,
  `name` TEXT(65534) NULL DEFAULT NULL,
  `like_count` bigint(250) NULL DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;